[naverpost_elle_loveandlife]
title = "네이버 포스트 ─ 엘르 코리아 ─ LOVE & LIFE"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=498784&memberNo=12504201"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_elle_shop]
title = "네이버 포스트 ─ 엘르 코리아 ─ 엘르숍"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=586118&memberNo=12504201"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_elle_beauty]
title = "네이버 포스트 ─ 엘르 코리아 ─ BEAUTY"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=498782&memberNo=12504201"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_elle_fashion]
title = "네이버 포스트 ─ 엘르 코리아 ─ FASHION"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=498781&memberNo=12504201"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_elle_star]
title = "네이버 포스트 ─ 엘르 코리아 ─ STAR"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=498783&memberNo=12504201"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_elle_notice]
title = "네이버 포스트 ─ 엘르 코리아 ─ NOTICE"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=645048&memberNo=12504201"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[fashion]
title = "엘르 코리아 ─ 패션"
url = "https://www.elle.co.kr/fashion"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120

[beauty]
title = "엘르 코리아 ─ 뷰티"
url = "https://www.elle.co.kr/beauty"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120

[star]
title = "엘르 코리아 ─ 스타"
url = "https://www.elle.co.kr/star"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[culture]
title = "엘르 코리아 ─ 컬쳐"
url = "https://www.elle.co.kr/culture"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"

[culture_music]
title = "엘르 코리아 ─ 컬쳐 ─ 뮤직"
url = "https://www.elle.co.kr/culture/music"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120

[culture_moviesandtv]
title = "엘르 코리아 ─ 컬쳐 ─ 무비&TV"
url = "https://www.elle.co.kr/culture/moviesandtv"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120

[culture_artanddesign]
title = "엘르 코리아 ─ 컬쳐 ─ 아트&디자인"
url = "https://www.elle.co.kr/culture/artanddesign"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120

[loveandlife]
title = "엘르 코리아 ─ 컬쳐 ─ 러브&라이프"
url = "https://www.elle.co.kr/loveandlife"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120

[society]
title = "엘르 코리아 ─ 소사이어티"
url = "https://www.elle.co.kr/society"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
timeout = 120
