[fashion]
title = "엘르 코리아 ─ 패션"
url = "https://www.elle.co.kr/fashion"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[beauty]
title = "엘르 코리아 ─ 뷰티"
url = "https://www.elle.co.kr/beauty"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[star]
title = "엘르 코리아 ─ 스타"
url = "https://www.elle.co.kr/star"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[culture]
title = "엘르 코리아 ─ 컬쳐"
url = "https://www.elle.co.kr/culture"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[culture_music]
title = "엘르 코리아 ─ 컬쳐 ─ 뮤직"
url = "https://www.elle.co.kr/culture/music"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[culture_moviesandtv]
title = "엘르 코리아 ─ 컬쳐 ─ 무비&TV"
url = "https://www.elle.co.kr/culture/moviesandtv"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[culture_artanddesign]
title = "엘르 코리아 ─ 컬쳐 ─ 아트&디자인"
url = "https://www.elle.co.kr/culture/artanddesign"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[loveandlife]
title = "엘르 코리아 ─ 컬쳐 ─ 러브&라이프"
url = "https://www.elle.co.kr/loveandlife"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"

[society]
title = "엘르 코리아 ─ 소사이어티"
url = "https://www.elle.co.kr/society"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitUntil = "networkidle"
